#include <iostream>
#include <map>
#include <string>
using namespace std;

class Duals {
	map<string, Skill> duals;
	
	public:
		void _init_();
		Skill getDual(string, string, string);
}
void Duals::_init_(){
	duals['terra_hydras'] = new Skill();
	duals['terra_aeris'] = new Skill();
	duals['terra_fire'] = new Skill();
	duals['terra_frost'] = new Skill();
	duals['terra_light'] = new Skill();
	duals['terra_strength'] = new Skill();
	duals['terra_step'] = new Skill();
	duals['terra_sense'] = new Skill();
	duals['terra_blink'] = new Skill();
	duals['terra_manifestation'] = new Skill();
	duals['terra_sight'] = new Skill();
	duals['terra_mend'] = new Skill();
	duals['terra_transference'] = new Skill();
	duals['terra_shift'] = new Skill();
	duals['hydras_aeris'] = new Skill();
	duals['hydras_fire'] = new Skill();
	duals['hydras_frost'] = new Skill();
	duals['hydras_light'] = new Skill();
	duals['hydras_strength'] = new Skill();
	duals['hydras_step'] = new Skill();
	duals['hydras_sense'] = new Skill();
	duals['hydras_blink'] = new Skill();
	duals['hydras_manifestation'] = new Skill();
	duals['hydras_sight'] = new Skill();
	duals['hydras_mend'] = new Skill();
	duals['hydras_transference'] = new Skill();
	duals['hydras_shift'] = new Skill();
	duals['aeris_fire'] = new Skill();
	duals['aeris_frost'] = new Skill();
	duals['aeris_light'] = new Skill();
	duals['aeris_strength'] = new Skill();
	duals['aeris_step'] = new Skill();
	duals['aeris_sense'] = new Skill();
	duals['aeris_blink'] = new Skill();
	duals['aeris_manifestation'] = new Skill();
	duals['aeris_sight'] = new Skill();
	duals['aeris_mend'] = new Skill();
	duals['aeris_transference'] = new Skill();
	duals['aeris_shift'] = new Skill();
	duals['fire_frost'] = new Skill();
	duals['fire_light'] = new Skill();
	duals['fire_strength'] = new Skill();
	duals['fire_step'] = new Skill();
	duals['fire_sense'] = new Skill();
	duals['fire_blink'] = new Skill();
	duals['fire_manifestation'] = new Skill();
	duals['fire_sight'] = new Skill();
	duals['fire_mend'] = new Skill();
	duals['fire_transference'] = new Skill();
	duals['fire_shift'] = new Skill();
	duals['frost_light'] = new Skill();
	duals['frost_strength'] = new Skill();
	duals['frost_step'] = new Skill();
	duals['frost_sense'] = new Skill();
	duals['frost_blink'] = new Skill();
	duals['frost_manifestation'] = new Skill();
	duals['frost_sight'] = new Skill();
	duals['frost_mend'] = new Skill();
	duals['frost_transference'] = new Skill();
	duals['frost_shift'] = new Skill();
	duals['light_strength'] = new Skill();
	duals['light_step'] = new Skill();
	duals['light_sense'] = new Skill();
	duals['light_blink'] = new Skill();
	duals['light_manifestation'] = new Skill();
	duals['light_sight'] = new Skill();
	duals['light_mend'] = new Skill();
	duals['light_transference'] = new Skill();
	duals['light_shift'] = new Skill();
	duals['strength_step'] = new Skill();
	duals['strength_sense'] = new Skill();
	duals['strength_blink'] = new Skill();
	duals['strength_manifestation'] = new Skill();
	duals['strength_sight'] = new Skill();
	duals['strength_mend'] = new Skill();
	duals['strength_transference'] = new Skill();
	duals['strength_shift'] = new Skill();
	duals['step_sense'] = new Skill();
	duals['step_blink'] = new Skill();
	duals['step_manifestation'] = new Skill();
	duals['step_sight'] = new Skill();
	duals['step_mend'] = new Skill();
	duals['step_transference'] = new Skill();
	duals['step_shift'] = new Skill();
	duals['sense_blink'] = new Skill();
	duals['sense_manifestation'] = new Skill();
	duals['sense_sight'] = new Skill();
	duals['sense_mend'] = new Skill();
	duals['sense_transference'] = new Skill();
	duals['sense_shift'] = new Skill();
	duals['blink_manifestation'] = new Skill();
	duals['blink_sight'] = new Skill();
	duals['blink_mend'] = new Skill();
	duals['blink_transference'] = new Skill();
	duals['blink_shift'] = new Skill();
	duals['manifestation_sight'] = new Skill();
	duals['manifestation_mend'] = new Skill();
	duals['manifestation_transference'] = new Skill();
	duals['manifestation_shift'] = new Skill();
	duals['sight_mend'] = new Skill();
	duals['sight_transference'] = new Skill();
	duals['sight_shift'] = new Skill();
	duals['mend_transference'] = new Skill();
	duals['mend_shift'] = new Skill();
	duals['transference_shift'] = new Skill();
}